#!/usr/bin/env python3
"""Generates Kante for KDE's Union style engine from tokens/palette.json.

  union/styles/kante/         Union CSS style, dark
  union/styles/kante-light/   Union CSS style, light ("Leinen")
  union/colors/Kante.colors, KanteLight.colors   KDE colour schemes (Plasma, Qt widgets, GTK)

Every style is metadata.json + contents/css/{style,variables,controls}.css. Only
variables.css is generated (colours as --k-* roles); controls.css is copied from
union/template/ and holds no raw colours. Edit tokens/palette.json or the template,
then run ./build.sh. Use it with:
  cp -r union/styles/kante ~/.local/share/union/css/styles/
  UNION_STYLE_NAME=kante QT_QUICK_CONTROLS_STYLE=org.kde.union <app>
Usage: python3 tools/build-union.py   (build.sh runs it)
"""
import importlib.util
import json
import shutil
from pathlib import Path

KANTE = Path(__file__).resolve().parent.parent
PALETTE = json.loads((KANTE / "tokens/palette.json").read_text())
UNION = KANTE / "union"

# Reuse the palette resolution of the QML build (token name / hex / [token, alpha]).
_spec = importlib.util.spec_from_file_location("build_qml", Path(__file__).with_name("build-qml.py"))
build_qml = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(build_qml)

STYLES = {
    "kante": {"theme": "dark", "name": "Kante", "scheme": "Kante", "description": "Kante for KDE Plasma: gruvbox ground, cyan focus, yellow primary."},
    "kante-light": {"theme": "light", "name": "Kante Light", "scheme": "KanteLight", "description": "Kante Light (Leinen) for KDE Plasma."},
}
HEADER = "Generated by kante/tools/build-union.py from kante/tokens/palette.json. Do not edit."


def rgb(hexv):
    hexv = hexv.lstrip("#")
    return tuple(int(hexv[i:i + 2], 16) for i in (0, 2, 4))


def css_color(value, tokens):
    """Role value -> a CSS colour: "#rrggbb", or rgba() when it has an alpha."""
    alpha = None
    if isinstance(value, list):
        value, alpha = value
    hexv = (value if value.startswith("#") else tokens[value]).lower()
    if alpha is None:
        return hexv
    r, g, b = rgb(hexv)
    return "rgba(%d, %d, %d, %s)" % (r, g, b, ("%.2f" % alpha).rstrip("0").rstrip("."))


def roles(theme):
    """The --k-* colour roles of one theme: name -> CSS colour."""
    tokens = build_qml.theme_tokens(theme)
    app = PALETTE["app"][theme]
    c = lambda v: css_color(v, tokens)
    field = tokens["bg-hard"] if theme == "dark" else tokens["bg1"]
    return {
        "ground": c(app["ground"]),
        "text": c(app["text"]),
        "text-strong": c(app["strongText"]),
        "text-muted": c(app["mutedText"]),
        "text-disabled": c(app["disabledText"]),
        "field": c(field),
        "card": c(app["card"]),
        "sunken": c(app["sunken"]),
        "frame": c(app["frame"]),
        "rule": c(app["rule"]),
        "primary": c(app["accent"]),
        "primary-hover": c(app["accentHover"]),
        "primary-pressed": c(app["accentPressed"]),
        "on-primary": c(app["accentForeground"]),
        "focus": c(app["focus"]),
        "selection": c(app["selection"]),
        "positive": c(app["positive"]),
        "neutral": c(app["neutral"]),
        "negative": c(app["negative"]),
        "info": c(app["info"]),
    }


def variables_css(style):
    shape = PALETTE["shape"]
    lines = ["/* %s */" % HEADER, "", ":root {", "    /* Colours */"]
    lines += ["    --k-%s: %s;" % (k, v) for k, v in roles(style["theme"]).items()]
    lines += [
        "",
        "    /* Metrics (Kante medium control height, 2 px focus ring) */",
        "    --k-control: %dpx;" % shape["heights"]["medium"],
        "    --k-gap: 4px;",
        "    --k-pad: 8px;",
        "    --k-field-width: 200px;",
        "}",
        "",
    ]
    return "\n".join(lines)


def style_css():
    return "/* %s */\n\n@import \"variables.css\";\n@import \"controls.css\";\n" % HEADER


def write_style(key, style):
    out = UNION / "styles" / key
    css = out / "contents/css"
    css.mkdir(parents=True, exist_ok=True)
    meta = {
        "input-type": "css",
        "input-version": 1,
        "name": style["name"],
        "description": style["description"],
        "version": PALETTE["meta"]["version"],
        "license": "MIT",
        "url": PALETTE["meta"]["source"],
        "authors": ["shrippen"],
    }
    (out / "metadata.json").write_text(json.dumps(meta, indent=4) + "\n")
    (css / "style.css").write_text(style_css())
    (css / "variables.css").write_text(variables_css(style))
    shutil.copy(UNION / "template/controls.css", css / "controls.css")


def section(name, bg, alt, fg, tokens, app, hover):
    """One [Colors:*] block of a KDE colour scheme."""
    rgbs = lambda v: ",".join(str(x) for x in rgb(v if v.startswith("#") else tokens[v]))
    rows = [
        ("BackgroundAlternate", alt),
        ("BackgroundNormal", bg),
        ("DecorationFocus", app["focus"]),
        ("DecorationHover", hover),
        ("ForegroundActive", app["focus"]),
        ("ForegroundInactive", app["disabledText"]),
        ("ForegroundLink", app["focus"]),
        ("ForegroundNegative", "red-text"),
        ("ForegroundNeutral", app["neutral"]),
        ("ForegroundNormal", fg),
        ("ForegroundPositive", app["positive"]),
        ("ForegroundVisited", app["tag"]),
    ]
    return "[Colors:%s]\n%s\n" % (name, "\n".join("%s=%s" % (k, rgbs(v)) for k, v in rows))


def colors_scheme(style):
    theme = style["theme"]
    tokens = build_qml.theme_tokens(theme)
    app = PALETTE["app"][theme]
    field = "bg-hard" if theme == "dark" else "bg1"
    tooltip = "bg0" if theme == "dark" else "bg1"
    parts = [
        "# %s" % HEADER,
        "[ColorEffects:Disabled]\nColor=56,56,56\nColorAmount=0\nColorEffect=0\nContrastAmount=0.65\nContrastEffect=1\nIntensityAmount=0.1\nIntensityEffect=2\n",
        "[ColorEffects:Inactive]\nChangeSelectionColor=true\nColor=112,111,110\nColorAmount=0.025\nColorEffect=2\nContrastAmount=0.1\nContrastEffect=2\nEnable=false\nIntensityAmount=0\nIntensityEffect=0\n",
        section("Button", "bg1", "bg2", app["text"], tokens, app, app["focus"]),
        section("Complementary", "bg-void", "bg-hard", app["text"], tokens, app, app["focus"]),
        section("Header", app["ground"], "bg0", app["text"], tokens, app, app["focus"]),
        section("Selection", app["selection"], "bg2", app["strongText"], tokens, app, app["focus"]),
        section("Tooltip", tooltip, "bg2", app["text"], tokens, app, app["focus"]),
        section("View", field, "bg0" if theme == "dark" else "bg-panel", app["text"], tokens, app, app["focus"]),
        section("Window", app["ground"], "bg0" if theme == "dark" else "bg-panel", app["text"], tokens, app, app["focus"]),
        "[General]\nColorScheme=%s\nName=%s\nshadeSortColumn=true\n" % (style["scheme"], style["name"]),
        "[KDE]\ncontrast=4\n",
        "[WM]\nactiveBackground=%s\nactiveForeground=%s\ninactiveBackground=%s\ninactiveForeground=%s\n" % (
            ",".join(str(x) for x in rgb(tokens[app["ground"]] if not app["ground"].startswith("#") else app["ground"])),
            ",".join(str(x) for x in rgb(tokens[app["text"]])),
            ",".join(str(x) for x in rgb(tokens["bg-void"])),
            ",".join(str(x) for x in rgb(tokens[app["disabledText"]])),
        ),
    ]
    return "\n".join(parts)


def main():
    (UNION / "colors").mkdir(parents=True, exist_ok=True)
    for key, style in STYLES.items():
        write_style(key, style)
        (UNION / "colors" / ("%s.colors" % style["scheme"])).write_text(colors_scheme(style))
    print("built union/styles/{kante,kante-light}, union/colors/{Kante,KanteLight}.colors")


if __name__ == "__main__":
    main()
